### PR TITLE
Add support for dedicated ip addresses

### PR DESCRIPTION
**Pull request by thrnz**
WIP. Currently untested.

### CODE REVIEW

**Comment by funkypenguin** [comment]
I've tested this and it works as expected 👍🏻

**Comment by funkypenguin** [comment]
> I've tested this and it works as expected 👍🏻

Correction. I have **not** tested this yet. (I thought I did but I ended up with old config)

**Comment by thrnz** [comment]
Thanks for trying to test this. It's mostly based on what PIA's own scripts do, but I don't have a decicated ip token to test it out myself.

Using this docker-compose might be the most conventient way of trying it out:

```
version: '3'
services:
    vpn:
        build: https://github.com/thrnz/docker-wireguard-pia.git#dip
        cap_add:
          - NET_ADMIN
        environment:
            - USER=xxxxxxxxxxxxxxxx
            - PASS=xxxxxxxxxxxxxxxx
            - PIA_DIP_TOKEN=xxxxxxxx
       sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        volumes:
            - pia:/pia

volumes:
    pia:
```

Docker should then hopefully build the container from the PR directly. If it works as expected, there should be some log messages along the lines of:

```
Fetching dedicated ip server info
Dedicated ip: x.x.x.x, cn: somehostname
```

It should then go on and connect as normal using the dedicated ip address.

**Comment by samcro1967** [comment]
Just tested this and it does not appear to be working.  It seems to have passed the token correctly and it got the correct IP address in the response even though it says it failed.
```
Fri Oct 13 17:44:55 UTC 2023: Fetching dedicated ip server info
Fri Oct 13 17:44:55 UTC 2023: Failed to fetch dedicated ip server info. Response:
[{"id":"ca_toronto","dip_token":"<redacted>","dip_expire":1701388800,"groups":["ovpntcp","ovpnudp","wg","ikev2"],"ip":"<redacted>","cn":"toronto427","status":"active"}]
Fri Oct 13 17:44:55 UTC 2023: Failed to generate WireGuard config
Fri Oct 13 17:44:55 UTC 2023: Fatal error
```

**Comment by thrnz** [comment]
Thanks for testing this out. Looks like I screwed up the syntax for the status check. I don't suppose fixing that was enough to get it going?

**Comment by samcro1967** [comment]
That seems to have gotten further, but is still not working.  No Internet connectivity once the container is up.

```
docker logs wireguard-pia
Fri Oct 13 20:06:52 UTC 2023: Fetching dedicated ip server info
Fri Oct 13 20:06:52 UTC 2023: Dedicated ip: 191.96.237.35, cn: toronto427
Registering public key with PIA dedicated ip endpoint; cn: toronto427, ip: <redacted>
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Fri Oct 13 20:06:53 UTC 2023: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.33.142.120 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n

interface: wg0
  public key: <redacted>
  private key: (hidden)
  listening port: 40740
  fwmark: 0xca6c

peer: <redacted>
  endpoint: <redacted>:1337
  allowed ips: 0.0.0.0/0

Fri Oct 13 20:06:53 UTC 2023: WireGuard successfully started
Fri Oct 13 20:06:53 UTC 2023: Allowing network access to 172.22.0.52/16 on eth0
Fri Oct 13 20:06:53 UTC 2023: Firewall enabled: Blocking non-WireGuard traffic
Fri Oct 13 20:06:53 UTC 2023: Allowing network access to 192.168.1.0/24 on eth0
Fri Oct 13 20:06:53 UTC 2023: Adding route to 192.168.1.0/24
Fri Oct 13 20:06:53 UTC 2023: Starting port forward script
Fri Oct 13 20:06:53 UTC 2023: Verifying API requests. CN: toronto427
Fri Oct 13 20:06:53 UTC 2023: Getting PF token
curl: (28) Failed to connect to toronto427 port 19999 after 30001 ms: Timeout was reached
curl: (28) Failed to connect to toronto427 port 19999 after 30002 ms: Timeout was reached
```

**Comment by thrnz** [comment]
I'll go back over their scripts and see if I'm missing anything.

Could you confirm that the container works as expected without the DIP stuff (ie. without `PIA_DIP_TOKEN` set) just to confirm that the issue is with these changes?

Does running `wg show` in the container show any handshakes or data transfer? Eg:

```
peer: xyz
  endpoint: xyz:1337
  allowed ips: 0.0.0.0/0
  latest handshake: 36 seconds ago
  transfer: 5.11 KiB received, 5.81 KiB sent

```

**Comment by thrnz** [comment]
I found one difference. When generating the wireguard config it looks like they use the given server ip address, whereas I'm using the `server_ip` from the `addKey` response.

I don't suppose the redacted ip from:

```Registering public key with PIA dedicated ip endpoint; cn: toronto427, ip: <redacted>```

differs from that in:
```
peer: <redacted>
  endpoint: <redacted>:1337
  allowed ips: 0.0.0.0/0
```

**Comment by samcro1967** [comment]
I just tested the latest changes you made and it appears to be working.  It connects, the dedicated IP address is assigned, and Internet connectivity is working.

**Comment by thrnz** [comment]
Excellent. Let me know if you notice any other issues and all going well I'll merge this soon.

Thanks for testing it out.

**Comment by samcro1967** [comment]
Everything has been working without any issues the past three days.

**Pull request merged**
